language: python
python:
  - "3.5"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
# command to install dependencies
install:
   - pip install flake8
   - pip install -r requirements.txt
# command to run tests
before_script:
- "sh -e /etc/init.d/xvfb start"
- "export DISPLAY=99:0"
- "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar"
- "java -jar selenium-server-standalone-2.43.1.jar > /dev/null &"

script:
  - python manage.py test
  - flake8
